### ISSUE TITLE
Possible tags to add

### ISSUE THREAD

**Issue by maxxer** [barrydegraaff/sa-alert-zimlet#1]
If you want to consider adding check for these tags:

HTTPS_HTTP_MISMATCH : emails with https link title but leading to an http href
URIBL_DBL_ABUSE_PHISH : Contains an abused phishing URL listed in the DBL blocklist
RCVD_IN_BRBL_LASTEXT : The last external relay in the Received chain was listed in the DNSBL Barracuda Reputation Block List (BRBL)
RCVD_IN_BL_SPAMCOP_NET : A relay in the message's Received headers was listed in the Spamcop DNSBL

**Comment by barrydegraaff** [comment]
fixed in https://github.com/barrydegraaff/sa-alert-zimlet/commit/3e72cfcce5253401872746d873e499175b01e5d1
